### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by Fafrin**
Czech translation from Czech Pirate Party.
For freedom!

### CODE REVIEW

**Comment by socialhack** [comment]
Thanks a lot for this translation. We are now looking for someone to review your translation before we can put it online.

**Comment by Fafrin** [comment]
Can I somehow help you get someone?

**Comment by socialhack** [comment]
please do, We just need independent verification that everything on your translation is correct. This is a volunteer run site. Just put us in contact via info ät savetheinternet (dot) eu

**Comment by digital-dreamer** [comment]
Hi @socialhack, you may remember me, I did the Czech translation of the last year's campaign. I just read all text in both files of this pull request, comparing all paragraphs to the English original. I can confirm this is indeed an accurate translation, and sound very professional. Excellent work :+1:

**Comment by lnovy** [comment]
Fahrin, plese use another branch than the master to request a merge from, look at the mess I just made because of you  :))

**Comment by Fafrin** [comment]
@lnovy I was following the instruction on "how to make a translation" in original.
If you wanted to fix html (even I spoted some unclosed tags during translation), you are the one who should crate now branch _from the original repository_.
I dont know how to fix that now. :/

**Comment by digital-dreamer** [comment]
@Fafrin - I know how to fix it, the pull request can still be merged manually - I can take just the first 3 commits and push them into the project's master branch. Is it OK if I do it, @socialhack?

**Comment by socialhack** [comment]
yes, please go ahead. Please give me a clean pull request I can easily merge. Thanks a lot guys!

**Comment by digital-dreamer** [comment]
@socialhack OK, that will work too. Here, it should be ready to merge: #69

**Comment by socialhack** [comment]
fixed by #69

**Pull request closed without merging**
